# Generated by Django 5.2.12 on 2026-03-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('food', models.CharField(max_length=100)),
                ('song', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('movie', models.CharField(max_length=100)),
                ('match_percentage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('q1_music', models.CharField(max_length=100)),
                ('q2_reaction', models.CharField(max_length=100)),
                ('q3_food', models.CharField(max_length=100)),
                ('q4_hangout', models.CharField(max_length=100)),
                ('q5_quality', models.CharField(max_length=100)),
                ('q6_values', models.CharField(max_length=100)),
                ('q7_nature', models.CharField(max_length=100)),
                ('q8_personality', models.CharField(max_length=100)),
                ('q9_time', models.CharField(max_length=100)),
                ('q10_career', models.CharField(max_length=100)),
                ('q11_overthinking', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlamResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('how_met', models.TextField()),
                ('first_impression', models.TextField()),
                ('favorite_thing', models.TextField()),
                ('describe_in_3_words', models.CharField(max_length=200)),
                ('perception_change', models.TextField()),
                ('vibe', models.CharField(max_length=100)),
                ('cute_habit', models.TextField()),
                ('change_habit', models.TextField()),
                ('grateful_for', models.TextField()),
                ('memory', models.TextField()),
                ('common_thing', models.TextField()),
                ('dedicated_song', models.CharField(max_length=200)),
                ('character_type', models.CharField(max_length=100)),
                ('things_to_try', models.TextField()),
                ('hobbies', models.TextField()),
                ('favorite_shows', models.TextField()),
                ('suggestions', models.TextField()),
                ('unsaid_thing', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
