# Generated by Django 5.2.12 on 2026-04-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('favorite_food', models.CharField(blank=True, max_length=255)),
                ('favorite_song_type', models.CharField(blank=True, max_length=255)),
                ('favorite_place', models.CharField(blank=True, max_length=255)),
                ('favorite_movie_vibe', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
